services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      /bin/bash -c "
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:16.2
    container_name: ${DATABASE_HOSTNAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "${CELERY_PORT}:${CELERY_PORT}"
    command: ["redis-server", "--timeout", "0"]
    restart: always

  celery_worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=${CELERY_DRIVER}://${CELERY_HOST}:${CELERY_PORT}/${CELERY_NAME}
    depends_on:
      - redis
      - db

  minio:
    image: minio/minio
    container_name: minio-server
    ports:
      - "${MINIO_PORT_API}:${MINIO_PORT_API}"
      - "${MINIO_PORT_CONSOLE}:${MINIO_PORT_CONSOLE}"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_PORT_CONSOLE}"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
