apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: postgres
    secureJsonData:
      password: 'postgres'
    isDefault: true
    jsonData:
      database: postgres
      sslmode: disable
      postgresVersion: 15
