{
 "title": "Images",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Time",
   "type": "barchart",
   "description": "Distribution of processed images by time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT i.created_at AS created_time, s.processing_time\r\nFROM imagetask i\r\nJOIN stats s ON i.id = s.image_id\r\nORDER BY created_time;\r\n"
    }
   ]
  },
  {
   "title": "Size",
   "type": "barchart",
   "description": "Distribution of processed images by size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT size, COUNT(*) as count\r\nFROM stats\r\nGROUP BY size\r\nORDER BY size;\r\n"
    }
   ]
  },
  {
   "title": "Width / Height",
   "type": "barchart",
   "description": "Distribution of processed images by width/height",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT width, height, COUNT(*) as count\r\nFROM stats\r\nGROUP BY width, height\r\nORDER BY count DESC;\r\n"
    }
   ]
  }
 ]
}